---
- hosts: nodes
  become: true

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update apt cache if needed
      apt: update_cache=true cache_valid_time=3600

  handlers:
    - name: restart solr
      service: name=colr state=restarted

  tasks:
    - name: Install Java
      apt: name=openjdk-8-jdk state=present

    - name: Download Solr
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/lucene/solr/{{solr_version}}/solr-{{solr_version}}-src.tgz?action=download"     
	dest: "{{ download_dir }}}/solr-{{solr_version}}.tgz"
   #   url: "https://dlcdn.apache.org/lucene/solr/{{solr_version}}/solr-{{solr_version}}-src.tgz"

    - name: Expand Solr
      unarchive:
        src: "{{ download_dir }}/solr-{{solr_version}}.tgz"
        dest: "{{download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{solr_version}}/README"

    - name: Run Solr Instalation Script
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /var/solr
        -u solr
        -s solr
        -p 8983
        creates:{{ solr_dir }}/bin/solr

    - name: Ensure solr is started and enbaled at boot
      service: name=solr state=started enabled=yes
